build:
  image: node:4
  commands:
    - npm run upload-artifacts --color
clone:
  depth: 10
cache:
  mount:
    - .git
    - node_modules
    - typings
environment:
  - CLICOLOR_FORCE=1
  - FORCE_COLOR=1
  - TERM=xterm-256color
publish:
  sftp-zh:
    host: dryclean.io
    port: 22
    username: $$SFTP_USERNAME
    password: $$SFTP_PASSWORD
    files: *.json
    destination_path: /var/www/drone-reports/branches/$$BRANCH/$$COMMIT