pipeline:
  test:
    image: node:4
    commands:
      - npm version

  drone-dryclean:
    image: colelawr/drone-dryclean
    debug: true
    host: cov.dryclean.io
    auth: super-secret-auth
    files:
      -
        path: ./reports/coverage/Phantom*/cobertura-coverage.xml
        label: Diff Cover Report
        loader: "dc-diff-cover?compare-branch=develop&fail-under=60&github=status"
      -
        path: ./reports/coverage/Phantom*/
        label: Coverage Report
        loader: "dc-coverage?json=final-report.json&github=comment-link"
      -
        path: ./reports/tslint-prose.txt
        label: tslint.txt
        loader: "dc-diff-lint?format=tslint-prose&github=status"

clone:
  depth: 5

environment:
  - CLICOLOR_FORCE=1
  - FORCE_COLOR=1
  - TERM=xterm-256color
