pipeline:
  test:
    image: node:4
    commands:
      - npm version

  drone-dryclean:
    image: colelawr/drone-dryclean
    debug: true
    host: cov.dryclean.io
    auth: super-secret-auth
    GITHUB_BOT_TOKEN: "dc53b37f216bfc6956570769c08ff5"
    GITHUB_BOT_USERNAME: "dryclean-bot"
    files:
        -
            path: ./coverage/Phantom*/coverage-final.json
            label: jasmine-coverage.json
            loader: "dctest?format=json"
        -
            path: ./tslint-prose.txt
            label: tslint.txt
            loader: "dclint?format=tslint-prose&github=true"

clone:
  depth: 5

environment:
  - CLICOLOR_FORCE=1
  - FORCE_COLOR=1
  - TERM=xterm-256color
