pipeline:
  test:
    image: node:4
    commands:
      - npm version

  publish:
    image: plugins/drone-dryclean
    host: cov.dryclean.io
    auth: super-secret-auth
    files:
        -
            path: ./coverage/Phantom*/coverage-final.json
            label: jasmine-coverage.json
            postprocessor: cobertura
        -
            path: ./tslint-checkstyle.txt
            label: tslint.txt
            postprocessor: checkstyle

clone:
  depth: 5

environment:
  - CLICOLOR_FORCE=1
  - FORCE_COLOR=1
  - TERM=xterm-256color
