pipeline:
  test:
    image: node:4
    commands:
      - npm version
      - git diff $DRONE_PREV_COMMIT_SHA $DRONE_COMMIT --name-only > last.diff

  diff-cover:
    image: dryclean/drone-diff-cover
    coverage: reports/coverage/Phantom*/cobertura-final.xml
    compare_branch: develop
    output: diff-cover.txt

clone:
  depth: 5

environment:
  - CLICOLOR_FORCE=1
  - FORCE_COLOR=1
  - TERM=xterm-256color
