build:
  image: node:4
  commands:
    - npm install --no-progress --color --quiet --unsafe-perm > npm-install.log
    - npm test --color
    - npm run upload-artifacts --color
clone:
  depth: 10
cache:
  mount:
    - .git
    - node_modules
    - typings
environment:
  - CLICOLOR_FORCE=1
  - FORCE_COLOR=1
  - TERM=xterm-256color
