pipeline:
  test:
    image: node:4
    commands:
      - npm run upload-artifacts --color

  artsy:
    host: cov.dryclean.io
    auth: super-secret-auth
    files:
        -
            path: ./coverage/Phantom*/coverage-final.json
            label: cover/json
            filename: coverage.json
            binary: false
        -
            path: ./tslint.json
            label: lint-rules/json
            filename: tslint.json

clone:
  depth: 5

environment:
  - CLICOLOR_FORCE=1
  - FORCE_COLOR=1
  - TERM=xterm-256color
