pipeline:
  test:
    image: node:4
    commands:
      - npm version

  dryclean:
    host: cov.dryclean.io
    auth: super-secret-auth
    files:
        -
            path: ./coverage/Phantom*/coverage-final.json
            label: Coverage.json
            postprocessor: cobertura
        -
            path: ./tslint.json
            label: codestyle.json
            postprocessor: lint

clone:
  depth: 5

environment:
  - CLICOLOR_FORCE=1
  - FORCE_COLOR=1
  - TERM=xterm-256color
